// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorboardX/proto/plugin_text.proto

#ifndef PROTOBUF_tensorboardX_2fproto_2fplugin_5ftext_2eproto__INCLUDED
#define PROTOBUF_tensorboardX_2fproto_2fplugin_5ftext_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace tensorboardX {
class TextPluginData;
class TextPluginDataDefaultTypeInternal;
extern TextPluginDataDefaultTypeInternal _TextPluginData_default_instance_;
}  // namespace tensorboardX

namespace tensorboardX {

namespace protobuf_tensorboardX_2fproto_2fplugin_5ftext_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_tensorboardX_2fproto_2fplugin_5ftext_2eproto

// ===================================================================

class TextPluginData : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:tensorboardX.TextPluginData) */ {
 public:
  TextPluginData();
  virtual ~TextPluginData();

  TextPluginData(const TextPluginData& from);

  inline TextPluginData& operator=(const TextPluginData& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TextPluginData& default_instance();

  static inline const TextPluginData* internal_default_instance() {
    return reinterpret_cast<const TextPluginData*>(
               &_TextPluginData_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(TextPluginData* other);

  // implements Message ----------------------------------------------

  inline TextPluginData* New() const PROTOBUF_FINAL { return New(NULL); }

  TextPluginData* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const TextPluginData& from);
  void MergeFrom(const TextPluginData& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(TextPluginData* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 version = 1;
  void clear_version();
  static const int kVersionFieldNumber = 1;
  ::google::protobuf::int32 version() const;
  void set_version(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:tensorboardX.TextPluginData)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 version_;
  mutable int _cached_size_;
  friend struct protobuf_tensorboardX_2fproto_2fplugin_5ftext_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// TextPluginData

// int32 version = 1;
inline void TextPluginData::clear_version() {
  version_ = 0;
}
inline ::google::protobuf::int32 TextPluginData::version() const {
  // @@protoc_insertion_point(field_get:tensorboardX.TextPluginData.version)
  return version_;
}
inline void TextPluginData::set_version(::google::protobuf::int32 value) {
  
  version_ = value;
  // @@protoc_insertion_point(field_set:tensorboardX.TextPluginData.version)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


}  // namespace tensorboardX

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_tensorboardX_2fproto_2fplugin_5ftext_2eproto__INCLUDED
